# alip's zprofile
# vim: set et sw=4 sts=4 ts=4 ft=zsh :

# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag). It's read after zshenv.
# Global Order: zshenv, zprofile, zshrc, zlogin

# rest is for non-root
(( EUID == 0 )) && return 0

# enable core dumps
ulimit -c unlimited

export CAVE_SEARCH_OPTIONS="--index /var/cache/paludis/index"

[[ -d "${HOME}"/Satranç ]] && export CHESSDIR="$HOME"/Satranç

# keychain
if [[ -z "${SSH_AGENT_PID}" ]] && type keychain &>/dev/null ; then
    eval $(keychain --quiet --eval id_dsa | sed -e 's,;,\n,g' )
fi
